// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type MetadataOrError interface {
	IsMetadataOrError()
}

type Product interface {
	IsProduct()
}

type Vehicle interface {
	IsVehicle()
}

type Book struct {
	Isbn           string    `json:"isbn"`
	Reviews        []*Review `json:"reviews"`
	SimilarBooks   []*Book   `json:"similarBooks"`
	RelatedReviews []*Review `json:"relatedReviews"`
}

func (Book) IsEntity()  {}
func (Book) IsProduct() {}

type Car struct {
	ID          string  `json:"id"`
	Price       *string `json:"price"`
	RetailPrice *string `json:"retailPrice"`
}

func (Car) IsEntity()  {}
func (Car) IsVehicle() {}

type Error struct {
	Code    *int    `json:"code"`
	Message *string `json:"message"`
}

func (Error) IsMetadataOrError() {}

type Furniture struct {
	Upc     string    `json:"upc"`
	Reviews []*Review `json:"reviews"`
}

func (Furniture) IsEntity()  {}
func (Furniture) IsProduct() {}

type KeyValue struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

func (KeyValue) IsMetadataOrError() {}

type ReviewProduct struct {
	Upc   string `json:"upc"`
	Body  string `json:"body"`
	Stars *int   `json:"stars"`
}

type UpdateReviewInput struct {
	ID   string  `json:"id"`
	Body *string `json:"body"`
}

type User struct {
	ID              string          `json:"id"`
	Username        *string         `json:"username"`
	Reviews         []*Review       `json:"reviews"`
	NumberOfReviews int             `json:"numberOfReviews"`
	Metadata        []*UserMetadata `json:"metadata"`
	GoodAddress     *bool           `json:"goodAddress"`
}

func (User) IsEntity() {}

type UserMetadata struct {
	Address *string `json:"address"`
}

type Van struct {
	ID          string  `json:"id"`
	Price       *string `json:"price"`
	RetailPrice *string `json:"retailPrice"`
}

func (Van) IsEntity()  {}
func (Van) IsVehicle() {}
