// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Product interface {
	IsProduct()
}

type Book struct {
	Isbn         string `json:"isbn"`
	InStock      *bool  `json:"inStock"`
	IsCheckedOut *bool  `json:"isCheckedOut"`
}

func (Book) IsEntity()  {}
func (Book) IsProduct() {}

type Furniture struct {
	Sku     string `json:"sku"`
	InStock *bool  `json:"inStock"`
	IsHeavy *bool  `json:"isHeavy"`
}

func (Furniture) IsEntity()  {}
func (Furniture) IsProduct() {}

type User struct {
	ID              string          `json:"id"`
	Metadata        []*UserMetadata `json:"metadata"`
	GoodDescription *bool           `json:"goodDescription"`
}

func (User) IsEntity() {}

type UserMetadata struct {
	Description *string `json:"description"`
}
