// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Body interface {
	IsBody()
}

type NamedObject interface {
	IsNamedObject()
	GetName() string
}

type Image struct {
	Name       string           `json:"name"`
	Attributes *ImageAttributes `json:"attributes"`
}

func (Image) IsBody() {}

func (Image) IsNamedObject()       {}
func (this Image) GetName() string { return this.Name }

type ImageAttributes struct {
	URL string `json:"url"`
}

type Noop struct {
	Noop *string `json:"noop"`
}

func (Noop) IsEntity() {}

type Text struct {
	Name       string          `json:"name"`
	Attributes *TextAttributes `json:"attributes"`
}

func (Text) IsBody() {}

func (Text) IsNamedObject()       {}
func (this Text) GetName() string { return this.Name }

type TextAttributes struct {
	Bold *bool   `json:"bold"`
	Text *string `json:"text"`
}
